# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#> .

`DateTimeX-Format-Ago`
	:test-requirement    [ :on "Test::More 0.96"^^:CpanId ];
	:runtime-requirement [ :on "perl 5.010"^^:CpanId ];
	:runtime-requirement [ :on "DateTime"^^:CpanId ].
